name: Setup Branch Protection

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to protect'
        required: true
        default: 'main'

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = '${{ github.event.inputs.branch_name }}';

            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch,
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'lint',
                    'type-check',
                    'test (3.8)',
                    'test (3.9)',
                    'test (3.10)',
                    'test (3.11)',
                    'test (3.12)',
                    'integration-test',
                    'docker-build',
                    'pre-commit'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true
              });

              console.log(`✅ Branch protection rules applied to ${branch}`);
            } catch (error) {
              console.error(`❌ Failed to setup branch protection: ${error.message}`);
              process.exit(1);
            }
